In [22]:
# Importing required libraries
import pandas as pd

In [23]:
# Loading our attrition data into a pandas dataframe
df = pd.read_csv(
    "../data/raw/WA_Fn-UseC_-HR-Employee-Attrition.csv"
)

# Visualizing top 5 records
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [24]:
# Checking missing values and percentual for all columns
df_summary = pd.DataFrame({
    'Data Type': df.dtypes,
    'Missing': df.isna().sum(),
    'Missing %': df.isna().mean() * 100,
})
df_summary

                         Data Type  Missing  Missing %
Age                          int64        0        0.0
Attrition                      str        0        0.0
BusinessTravel                 str        0        0.0
DailyRate                    int64        0        0.0
Department                     str        0        0.0
DistanceFromHome             int64        0        0.0
Education                    int64        0        0.0
EducationField                 str        0        0.0
EmployeeCount                int64        0        0.0
EmployeeNumber               int64        0        0.0
EnvironmentSatisfaction      int64        0        0.0
Gender                         str        0        0.0
HourlyRate                   int64        0        0.0
JobInvolvement               int64        0        0.0
JobLevel                     int64        0        0.0
JobRole                        str        0        0.0
JobSatisfaction              int64        0        0.0
MaritalStatus                  str        0        0.0
MonthlyIncome                int64        0        0.0
MonthlyRate                  int64        0        0.0
NumCompaniesWorked           int64        0        0.0
Over18                         str        0        0.0
OverTime                       str        0        0.0
PercentSalaryHike            int64        0        0.0
PerformanceRating            int64        0        0.0
RelationshipSatisfaction     int64        0        0.0
StandardHours                int64        0        0.0
StockOptionLevel             int64        0        0.0
TotalWorkingYears            int64        0        0.0
TrainingTimesLastYear        int64        0        0.0
WorkLifeBalance              int64        0        0.0
YearsAtCompany               int64        0        0.0
YearsInCurrentRole           int64        0        0.0
YearsSinceLastPromotion      int64        0        0.0
YearsWithCurrManager         int64        0        0.0

#### **Conclusion :** 
- The data quality assessment shows that there are **no missing values** across any of the 35 columns in the dataset. Each column has **0 missing values and a missing percentage of 0.0%**, indicating that the dataset is complete with respect to missing data. Therefore, **no data imputation or removal of records due to missing values is required** at this stage of the analysis. The dataset can proceed to the next stages of data exploration and analysis without the need for missing-value treatment.