In [99]:
import pandas as pd

df = pd.read_csv("../data/raw/WA_Fn-UseC_-HR-Employee-Attrition.csv")

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [100]:
yn_map = {
    'No': 0,
    'Yes': 1
}
df['Attrition'] = df['Attrition'].map(yn_map)
print(df['Attrition'].unique())

[1 0]

In [101]:
#Maps yes/no into numeric values. Yes: 1, No: 0
df['OverTime'] = df['OverTime'].map(yn_map)
print(df['OverTime'].unique())

[1 0]

In [102]:
#Splits gender into the available categories
df = pd.get_dummies(df, 
        columns=['BusinessTravel',
        'Department',
        'EducationField',
        'Gender',
        'JobRole',
        'MaritalStatus'],
        dtype=int)
df_summary = pd.DataFrame({
    'Data Type': df.dtypes,
    'Unique': df.nunique()
})
df_summary

                                  Data Type  Unique
Age                                   int64      43
Attrition                             int64       2
DailyRate                             int64     886
DistanceFromHome                      int64      29
Education                             int64       5
EmployeeCount                         int64       1
EmployeeNumber                        int64    1470
EnvironmentSatisfaction               int64       4
HourlyRate                            int64      71
JobInvolvement                        int64       4
JobLevel                              int64       5
JobSatisfaction                       int64       4
MonthlyIncome                         int64    1349
MonthlyRate                           int64    1427
NumCompaniesWorked                    int64      10
Over18                                  str       1
OverTime                              int64       2
PercentSalaryHike                     int64      15
PerformanceRating                     int64       2
RelationshipSatisfaction              int64       4
StandardHours                         int64       1
StockOptionLevel                      int64       4
TotalWorkingYears                     int64      40
TrainingTimesLastYear                 int64       7
WorkLifeBalance                       int64       4
YearsAtCompany                        int64      37
YearsInCurrentRole                    int64      19
YearsSinceLastPromotion               int64      16
YearsWithCurrManager                  int64      18
BusinessTravel_Non-Travel             int64       2
BusinessTravel_Travel_Frequently      int64       2
BusinessTravel_Travel_Rarely          int64       2
Department_Human Resources            int64       2
Department_Research & Development     int64       2
Department_Sales                      int64       2
EducationField_Human Resources        int64       2
EducationField_Life Sciences          int64       2
EducationField_Marketing              int64       2
EducationField_Medical                int64       2
EducationField_Other                  int64       2
EducationField_Technical Degree       int64       2
Gender_Female                         int64       2
Gender_Male                           int64       2
JobRole_Healthcare Representative     int64       2
JobRole_Human Resources               int64       2
JobRole_Laboratory Technician         int64       2
JobRole_Manager                       int64       2
JobRole_Manufacturing Director        int64       2
JobRole_Research Director             int64       2
JobRole_Research Scientist            int64       2
JobRole_Sales Executive               int64       2
JobRole_Sales Representative          int64       2
MaritalStatus_Divorced                int64       2
MaritalStatus_Married                 int64       2
MaritalStatus_Single                  int64       2

In [103]:
df[['MonthlyIncome', 'MonthlyRate','HourlyRate']].describe()

       MonthlyIncome   MonthlyRate   HourlyRate
count    1470.000000   1470.000000  1470.000000
mean     6502.931293  14313.103401    65.891156
std      4707.956783   7117.786044    20.329428
min      1009.000000   2094.000000    30.000000
25%      2911.000000   8047.000000    48.000000
50%      4919.000000  14235.500000    66.000000
75%      8379.000000  20461.500000    83.750000
max     19999.000000  26999.000000   100.000000

In [ ]:
#There is only two numbers for peformance rating.
#Converting them to only one and zero seems like a logical approach
df['PerformanceRating'] = df['PerformanceRating'].map({3:0, 4:1})
df['PerformanceRating']

0       0
1       1
2       0
3       0
4       0
       ..
1465    0
1466    0
1467    1
1468    0
1469    0
Name: PerformanceRating, Length: 1470, dtype: int64

In [106]:
from sklearn.preprocessing import StandardScaler

numeric_cols = [
    'Age',
    'DailyRate',
    'DistanceFromHome',
    'HourlyRate',
    'MonthlyIncome',
    'MonthlyRate',
    'NumCompaniesWorked',
    'PercentSalaryHike',
    'TotalWorkingYears',
    'TrainingTimesLastYear',
    'YearsAtCompany',
    'YearsInCurrentRole',
    'YearsSinceLastPromotion',
    'YearsWithCurrManager'
]

scaler = StandardScaler()

df[[numeric_cols]] = scaler.fit_transform(df[numeric_cols])
df.describe()

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
#Removed columns that had no predictive variablity (i.e. only one unique value)
#df = df.drop(columns=['EmployeeNumber', 'EmployeeCount', 'Over18', 'StandardHours'])