In [109]:
import pandas as pd

df = pd.read_csv("../data/raw/WA_Fn-UseC_-HR-Employee-Attrition.csv")

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [110]:
yn_map = {
    'No': 0,
    'Yes': 1
}
df['Attrition'] = df['Attrition'].map(yn_map)
print(df['Attrition'].unique())

[1 0]

In [111]:
#Maps yes/no into numeric values. Yes: 1, No: 0
df['OverTime'] = df['OverTime'].map(yn_map)
print(df['OverTime'].unique())

[1 0]

In [112]:
#Splits gender into the available categories
df = pd.get_dummies(df, 
        columns=['BusinessTravel',
        'Department',
        'EducationField',
        'Gender',
        'JobRole',
        'MaritalStatus'],
        dtype=int)
df_summary = pd.DataFrame({
    'Data Type': df.dtypes,
    'Unique': df.nunique()
})
df_summary

                                  Data Type  Unique
Age                                   int64      43
Attrition                             int64       2
DailyRate                             int64     886
DistanceFromHome                      int64      29
Education                             int64       5
EmployeeCount                         int64       1
EmployeeNumber                        int64    1470
EnvironmentSatisfaction               int64       4
HourlyRate                            int64      71
JobInvolvement                        int64       4
JobLevel                              int64       5
JobSatisfaction                       int64       4
MonthlyIncome                         int64    1349
MonthlyRate                           int64    1427
NumCompaniesWorked                    int64      10
Over18                                  str       1
OverTime                              int64       2
PercentSalaryHike                     int64      15
PerformanceRating                     int64       2
RelationshipSatisfaction              int64       4
StandardHours                         int64       1
StockOptionLevel                      int64       4
TotalWorkingYears                     int64      40
TrainingTimesLastYear                 int64       7
WorkLifeBalance                       int64       4
YearsAtCompany                        int64      37
YearsInCurrentRole                    int64      19
YearsSinceLastPromotion               int64      16
YearsWithCurrManager                  int64      18
BusinessTravel_Non-Travel             int64       2
BusinessTravel_Travel_Frequently      int64       2
BusinessTravel_Travel_Rarely          int64       2
Department_Human Resources            int64       2
Department_Research & Development     int64       2
Department_Sales                      int64       2
EducationField_Human Resources        int64       2
EducationField_Life Sciences          int64       2
EducationField_Marketing              int64       2
EducationField_Medical                int64       2
EducationField_Other                  int64       2
EducationField_Technical Degree       int64       2
Gender_Female                         int64       2
Gender_Male                           int64       2
JobRole_Healthcare Representative     int64       2
JobRole_Human Resources               int64       2
JobRole_Laboratory Technician         int64       2
JobRole_Manager                       int64       2
JobRole_Manufacturing Director        int64       2
JobRole_Research Director             int64       2
JobRole_Research Scientist            int64       2
JobRole_Sales Executive               int64       2
JobRole_Sales Representative          int64       2
MaritalStatus_Divorced                int64       2
MaritalStatus_Married                 int64       2
MaritalStatus_Single                  int64       2

In [114]:
#There is only two numbers for peformance rating.
#Converting them to only one and zero seems like a logical approach
df['PerformanceRating'] = df['PerformanceRating'].map({3:0, 4:1})
df['PerformanceRating']

0       0
1       1
2       0
3       0
4       0
       ..
1465    0
1466    0
1467    1
1468    0
1469    0
Name: PerformanceRating, Length: 1470, dtype: int64

In [117]:
from sklearn.preprocessing import StandardScaler

numeric_cols = [
    'Age',
    'DailyRate',
    'DistanceFromHome',
    'HourlyRate',
    'MonthlyIncome',
    'MonthlyRate',
    'NumCompaniesWorked',
    'PercentSalaryHike',
    'TotalWorkingYears',
    'TrainingTimesLastYear',
    'YearsAtCompany',
    'YearsInCurrentRole',
    'YearsSinceLastPromotion',
    'YearsWithCurrManager'
]

scaler = StandardScaler()

df[numeric_cols] = scaler.fit_transform(df[numeric_cols])
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,1470.0,-2.114711e-17,1.000340,-2.072192,-0.758170,-0.101159,0.665354,2.526886
Attrition,1470.0,1.612245e-01,0.367863,0.000000,0.000000,0.000000,0.000000,1.000000
DailyRate,1470.0,3.625218e-17,1.000340,-1.736576,-0.836662,-0.001204,0.878877,1.726730
DistanceFromHome,1470.0,2.900174e-17,1.000340,-1.010909,-0.887515,-0.270544,0.593216,2.444129
Education,1470.0,2.912925e+00,1.024165,1.000000,2.000000,3.000000,4.000000,5.000000
EnvironmentSatisfaction,1470.0,2.721769e+00,1.093082,1.000000,2.000000,3.000000,4.000000,4.000000
HourlyRate,1470.0,-2.900174e-17,1.000340,-1.766079,-0.880361,0.005356,0.878771,1.678377
JobInvolvement,1470.0,2.729932e+00,0.711561,1.000000,2.000000,3.000000,3.000000,4.000000
JobLevel,1470.0,2.063946e+00,1.106940,1.000000,1.000000,2.000000,3.000000,5.000000
JobSatisfaction,1470.0,2.728571e+00,1.102846,1.000000,2.000000,3.000000,4.000000,4.000000
MonthlyIncome,1470.0,-5.196146e-17,1.000340,-1.167343,-0.763209,-0.336552,0.398625,2.867626
MonthlyRate,1470.0,2.175131e-17,1.000340,-1.717284,-0.880644,-0.010906,0.864101,1.782888
NumCompaniesWorked,1470.0,2.175131e-17,1.000340,-1.078504,-0.678049,-0.277594,0.523316,2.525591
OverTime,1470.0,2.829932e-01,0.450606,0.000000,0.000000,0.000000,1.000000,1.000000
PercentSalaryHike,1470.0,-3.141856e-17,1.000340,-1.150554,-0.877232,-0.330589,0.762698,2.675949
PerformanceRating,1470.0,1.537415e-01,0.360824,0.000000,0.000000,0.000000,0.000000,1.000000
RelationshipSatisfaction,1470.0,2.712245e+00,1.081209,1.000000,2.000000,3.000000,4.000000,4.000000
StockOptionLevel,1470.0,7.938776e-01,0.852077,0.000000,0.000000,1.000000,1.000000,3.000000
TotalWorkingYears,1470.0,-1.208406e-18,1.000340,-1.450167,-0.678774,-0.164511,0.478316,3.692454
TrainingTimesLastYear,1470.0,1.208406e-17,1.000340,-2.171982,-0.620189,0.155707,0.155707,2.483396
WorkLifeBalance,1470.0,2.761224e+00,0.706476,1.000000,2.000000,3.000000,3.000000,4.000000
YearsAtCompany,1470.0,-7.250436e-18,1.000340,-1.144294,-0.654454,-0.327893,0.325228,5.386914
YearsInCurrentRole,1470.0,3.866899e-17,1.000340,-1.167687,-0.615492,-0.339394,0.764998,3.802074
YearsSinceLastPromotion,1470.0,-1.329247e-17,1.000340,-0.679146,-0.679146,-0.368715,0.252146,3.977310
YearsWithCurrManager,1470.0,0.000000e+00,1.000340,-1.155935,-0.595227,-0.314873,0.806541,3.610079
BusinessTravel_Non-Travel,1470.0,1.020408e-01,0.302805,0.000000,0.000000,0.000000,0.000000,1.000000
BusinessTravel_Travel_Frequently,1470.0,1.884354e-01,0.391193,0.000000,0.000000,0.000000,0.000000,1.000000
BusinessTravel_Travel_Rarely,1470.0,7.095238e-01,0.454137,0.000000,0.000000,1.000000,1.000000,1.000000
Department_Human Resources,1470.0,4.285714e-02,0.202604,0.000000,0.000000,0.000000,0.000000,1.000000
Department_Research & Development,1470.0,6.537415e-01,0.475939,0.000000,0.000000,1.000000,1.000000,1.000000
Department_Sales,1470.0,3.034014e-01,0.459884,0.000000,0.000000,0.000000,1.000000,1.000000
EducationField_Human Resources,1470.0,1.836735e-02,0.134321,0.000000,0.000000,0.000000,0.000000,1.000000
EducationField_Life Sciences,1470.0,4.122449e-01,0.492406,0.000000,0.000000,0.000000,1.000000,1.000000
EducationField_Marketing,1470.0,1.081633e-01,0.310692,0.000000,0.000000,0.000000,0.000000,1.000000
EducationField_Medical,1470.0,3.156463e-01,0.464931,0.000000,0.000000,0.000000,1.000000,1.000000
EducationField_Other,1470.0,5.578231e-02,0.229579,0.000000,0.000000,0.000000,0.000000,1.000000
EducationField_Technical Degree,1470.0,8.979592e-02,0.285986,0.000000,0.000000,0.000000,0.000000,1.000000
Gender_Female,1470.0,4.000000e-01,0.490065,0.000000,0.000000,0.000000,1.000000,1.000000
Gender_Male,1470.0,6.000000e-01,0.490065,0.000000,0.000000,1.000000,1.000000,1.000000
JobRole_Healthcare Representative,1470.0,8.911565e-02,0.285008,0.000000,0.000000,0.000000,0.000000,1.000000
JobRole_Human Resources,1470.0,3.537415e-02,0.184786,0.000000,0.000000,0.000000,0.000000,1.000000
JobRole_Laboratory Technician,1470.0,1.761905e-01,0.381112,0.000000,0.000000,0.000000,0.000000,1.000000
JobRole_Manager,1470.0,6.938776e-02,0.254199,0.000000,0.000000,0.000000,0.000000,1.000000
JobRole_Manufacturing Director,1470.0,9.863946e-02,0.298279,0.000000,0.000000,0.000000,0.000000,1.000000
JobRole_Research Director,1470.0,5.442177e-02,0.226925,0.000000,0.000000,0.000000,0.000000,1.000000
JobRole_Research Scientist,1470.0,1.986395e-01,0.399112,0.000000,0.000000,0.000000,0.000000,1.000000
JobRole_Sales Executive,1470.0,2.217687e-01,0.415578,0.000000,0.000000,0.000000,0.000000,1.000000
JobRole_Sales Representative,1470.0,5.646259e-02,0.230891,0.000000,0.000000,0.000000,0.000000,1.000000
MaritalStatus_Divorced,1470.0,2.224490e-01,0.416033,0.000000,0.000000,0.000000,0.000000,1.000000
MaritalStatus_Married,1470.0,4.578231e-01,0.498387,0.000000,0.000000,0.000000,1.000000,1.000000
MaritalStatus_Single,1470.0,3.197279e-01,0.466530,0.000000,0.000000,0.000000,1.000000,1.000000

In [ ]:
#Removed columns that had no predictive variablity (i.e. only one unique value) and employee number
df = df.drop(columns=['EmployeeNumber', 'EmployeeCount', 'Over18', 'StandardHours'])