# Data Wrangling – HR Employee Attrition Dataset

The objective of this notebook is to transform the cleaned and normalized HR Employee Attrition dataset into a structured and analysis-ready format.

Data wrangling involves organizing, transforming, and creating meaningful variables from the existing data to support further analysis.

In [4]:
# Import Libraries and Load Data
import pandas as pd
import numpy as np
df = pd.read_csv("../data/raw/WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [5]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [3]:
df.shape

(1470, 35)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 402.1 KB

# Select relevant columns
Selected the variables that are most relevant to understanding employee attrition and created a separate analysis dataset.

In [7]:
attrition_df = df[
    [
        'Attrition',
        'Age',
        'Gender',
        'Department',
        'JobRole',
        'JobLevel',
        'MonthlyIncome',
        'OverTime',
        'JobSatisfaction',
        'WorkLifeBalance',
        'TotalWorkingYears',
        'YearsAtCompany',
        'YearsSinceLastPromotion',
        'DistanceFromHome'
    ]
].copy()

In [8]:
# Converted Yes and No into 1 and 0 so these binary variables can be easily used in calculations.
attrition_df['Attrition'] = attrition_df['Attrition'].map({
    'Yes': 1,
    'No': 0
})

attrition_df['OverTime'] = attrition_df['OverTime'].map({
    'Yes': 1,
    'No': 0
})

# Create age and tenure groups to make it easier to compare employee attrition across different employee groups.

In [9]:
# Age Group
attrition_df['AgeGroup'] = pd.cut(
    attrition_df['Age'],
    bins=[0, 30, 40, 50, 100],
    labels=['Under 30', '30-39', '40-49', '50+']
)

In [10]:
#Tenure Group
attrition_df['TenureGroup'] = pd.cut(
    attrition_df['YearsAtCompany'],
    bins=[-1, 2, 5, 10, 100],
    labels=['0-2 Years', '3-5 Years', '6-10 Years', '10+ Years']
)

In [ ]:
# Grouped the data by department and calculated the total employees, employees who left, and attrition rate.
department_summary = (
    attrition_df
    .groupby('Department')
    .agg(
        TotalEmployees=('Attrition', 'count'),
        EmployeesLeft=('Attrition', 'sum'),
        AttritionRate=('Attrition', 'mean')
    )
    .reset_index()
)

department_summary['AttritionRate'] = (
    department_summary['AttritionRate'] * 100
).round(2)

department_summary

               Department  TotalEmployees  EmployeesLeft  AttritionRate
0         Human Resources              63             12          19.05
1  Research & Development             961            133          13.84
2                   Sales             446             92          20.63

# Validate the transformed dataset and save it as a separate wrangled dataset

In [12]:
attrition_df.head()

,Attrition,Age,Gender,Department,JobRole,JobLevel,MonthlyIncome,OverTime,JobSatisfaction,WorkLifeBalance,TotalWorkingYears,YearsAtCompany,YearsSinceLastPromotion,DistanceFromHome,AgeGroup,TenureGroup
0,1,41,Female,Sales,Sales Executive,2,5993,1,4,1,8,6,0,1,40-49,6-10 Years
1,0,49,Male,Research & Development,Research Scientist,2,5130,0,2,3,10,10,1,8,40-49,6-10 Years
2,1,37,Male,Research & Development,Laboratory Technician,1,2090,1,3,3,7,0,0,2,30-39,0-2 Years
3,0,33,Female,Research & Development,Research Scientist,1,2909,1,3,3,8,8,3,3,30-39,6-10 Years
4,0,27,Male,Research & Development,Laboratory Technician,1,3468,0,2,3,6,2,2,2,Under 30,0-2 Years

In [13]:
attrition_df.shape

(1470, 16)

In [14]:
attrition_df.isnull().sum().sum()

np.int64(0)

In [ ]:
attrition_df.to_csv(
    "../data/wrangled/HR_Employee_Attrition_Wrangled.csv",
    index=False
)

## Conclusion

The cleaned HR Employee Attrition dataset was transformed into an analysis-ready format through data-wrangling techniques.

The main steps included selecting relevant variables, converting binary Yes/No values into 1 and 0, creating meaningful Age and Tenure groups, and generating a department-level summary of employee attrition.

The transformed dataset was validated and saved separately for use in further analysis. These steps help make the data easier to understand and support the next stages of the project.